import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { useBroadcastStore } from '../../store/useBroadcastStore';
export const BattingScorecard = () => {
    const { teamA, teamB, battingTeamId, matchDetails } = useBroadcastStore();
    const battingTeam = battingTeamId === teamA.id ? teamA : teamB;
    const totalBalls = battingTeam.overs * 6 + battingTeam.balls;
    const crr = totalBalls > 0 ? ((battingTeam.score / totalBalls) * 6).toFixed(2) : '0.00';
    return (_jsx("div", { className: "absolute inset-0 flex items-center justify-center pointer-events-none z-40", children: _jsxs(motion.div, { initial: { opacity: 0, scale: 0.9, y: 30 }, animate: { opacity: 1, scale: 1, y: 0 }, exit: { opacity: 0, scale: 0.9, y: 30 }, transition: { type: 'spring', damping: 24, stiffness: 220 }, className: "w-[1000px] pointer-events-auto shadow-[0_0_60px_rgba(249,115,22,0.8)] rounded-xl overflow-hidden border-4 border-orange-500 bg-[#090d16] font-sans text-white", children: [_jsxs("div", { className: "bg-slate-950 border-b-2 border-orange-500 px-6 py-4 flex items-center justify-center relative overflow-hidden", children: [_jsx("div", { className: "absolute inset-x-4 top-1 bottom-1 border-y border-orange-500/40 pointer-events-none" }), _jsx("h2", { className: "text-3xl font-black uppercase tracking-widest text-center text-white", children: battingTeam.fullName })] }), _jsxs("div", { className: "bg-slate-900 border-b border-white/10 px-6 py-2 text-center text-xs font-black uppercase tracking-widest text-slate-300", children: [matchDetails.stage, " | ", matchDetails.title] }), _jsx("div", { className: "p-6 space-y-2.5", children: battingTeam.batters.map((b) => (_jsxs("div", { className: `px-5 py-3 rounded-lg flex items-center justify-between font-black text-sm border shadow ${!b.isOut
                            ? 'bg-gradient-to-r from-red-600 via-rose-600 to-red-600 text-white border-red-400/50'
                            : 'bg-slate-950/80 text-slate-200 border-white/10'}`, children: [_jsx("span", { className: "uppercase tracking-wide w-64", children: b.name }), _jsx("span", { className: "text-xs font-semibold text-slate-300 flex-1 text-center truncate px-4", children: b.isOut ? b.dismissal || 'out' : 'NOT OUT' }), _jsxs("div", { className: "flex items-center gap-6 font-black text-base", children: [_jsx("span", { className: "text-amber-300", children: b.runs }), _jsx("span", { className: "text-slate-300 text-xs", children: b.balls })] })] }, b.id))) }), _jsxs("div", { className: "bg-slate-950 border-t-2 border-orange-500 px-8 py-4 flex items-center justify-between text-base font-black uppercase", children: [_jsxs("div", { className: "flex items-center gap-8", children: [_jsxs("div", { children: [_jsx("span", { className: "text-slate-400 text-xs font-bold block", children: "RUN-RATE" }), _jsx("span", { className: "text-white text-xl", children: crr })] }), _jsxs("div", { children: [_jsx("span", { className: "text-slate-400 text-xs font-bold block", children: "EXTRAS" }), _jsx("span", { className: "text-white text-xl", children: "0" })] }), _jsxs("div", { children: [_jsx("span", { className: "text-slate-400 text-xs font-bold block", children: "OVERS" }), _jsx("span", { className: "text-white text-xl", children: battingTeam.overs })] })] }), _jsxs("div", { className: "text-right text-3xl font-black tracking-tight text-white", children: [battingTeam.score, " - ", battingTeam.wickets] })] })] }) }));
};
