import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { useBroadcastStore } from '../../store/useBroadcastStore';
export const BowlerStatisticsOverlay = () => {
    const { teamA, teamB, battingTeamId } = useBroadcastStore();
    const bowlingTeam = battingTeamId === teamA.id ? teamB : teamA;
    const currentBowler = bowlingTeam.bowlers.find((bw) => bw.isCurrent) || bowlingTeam.bowlers[0];
    return (_jsxs(motion.div, { initial: { x: 100, opacity: 0 }, animate: { x: 0, opacity: 1 }, exit: { x: 100, opacity: 0 }, transition: { type: 'spring', damping: 25, stiffness: 240 }, className: "absolute right-6 top-16 z-40 w-72 bg-gradient-to-b from-red-700 via-red-800 to-red-950 rounded-2xl shadow-2xl border-2 border-white/30 overflow-hidden font-sans text-white", children: [_jsxs("div", { className: "bg-black/40 py-2 text-center border-b border-white/20", children: [_jsx("span", { className: "text-[11px] font-black tracking-widest uppercase text-amber-300", children: "THIS TOURNAMENT" }), _jsx("h2", { className: "text-xl font-black uppercase text-white tracking-wide", children: currentBowler?.name || 'M STARC' }), _jsxs("span", { className: "text-xs font-bold opacity-80 uppercase", children: ["(", bowlingTeam.shortName, ")"] })] }), _jsx("div", { className: "flex justify-center my-3", children: _jsx("div", { className: "w-24 h-24 rounded-full bg-slate-900 border-4 border-white/40 flex items-center justify-center font-black text-2xl text-cyan-300 shadow-xl overflow-hidden", children: currentBowler?.name ? currentBowler.name.substring(0, 2).toUpperCase() : 'MS' }) }), _jsxs("div", { className: "p-3 bg-black/30 space-y-1.5 text-xs font-extrabold border-t border-white/10", children: [_jsxs("div", { className: "flex justify-between border-b border-white/10 pb-1", children: [_jsx("span", { className: "opacity-80", children: "MATCHES" }), _jsx("span", { children: "1" })] }), _jsxs("div", { className: "flex justify-between border-b border-white/10 pb-1", children: [_jsx("span", { className: "opacity-80", children: "WICKETS" }), _jsx("span", { className: "text-amber-300", children: currentBowler?.wickets || 0 })] }), _jsxs("div", { className: "flex justify-between border-b border-white/10 pb-1", children: [_jsx("span", { className: "opacity-80", children: "OVERS BOWLED" }), _jsxs("span", { children: [currentBowler?.overs || 0, ".", currentBowler?.ballsInCurrentOver || 0] })] }), _jsxs("div", { className: "flex justify-between border-b border-white/10 pb-1", children: [_jsx("span", { className: "opacity-80", children: "RUNS CONCEDED" }), _jsx("span", { children: currentBowler?.runsConceded || 0 })] }), _jsxs("div", { className: "flex justify-between border-b border-white/10 pb-1", children: [_jsx("span", { className: "opacity-80", children: "ECONOMY" }), _jsx("span", { className: "text-cyan-300", children: currentBowler?.overs ? (currentBowler.runsConceded / currentBowler.overs).toFixed(2) : '0.00' })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "opacity-80", children: "BEST" }), _jsxs("span", { children: [currentBowler?.wickets || 0, "/", currentBowler?.runsConceded || 0] })] })] })] }));
};
