// =============================================================================
// scoreboardThemes.ts — 19 complete scoreboard overlay themes matching CrickPro
// Used by ScoreboardOverlay.tsx and scoreboard-overlay.html
// =============================================================================

export type ThemeId =
  | 'nakshatra'
  | 'agni'
  | 'apex'
  | 'aranyaka'
  | 'volt'
  | 'thunder'
  | 'africa'
  | 'elite'
  | 'franchise'
  | 'blitz'
  | 'asia2021'
  | 'asia2022'
  | 'asia'
  | 'championship2019'
  | 'championship2022'
  | 'dharma'
  | 'shakti'
  | 'buzz'
  | 'diamond';

export type CelebrationStyle = 'ticker-takeover' | 'page-center' | 'batter-bar';
export type LayoutVariant = 'standard' | 'pill' | 'centered' | 'hundred';
export type AnimationVariant = 'slot-machine' | 'flip' | 'fade' | 'typewriter';

export interface ScoreboardTheme {
  id: ThemeId;
  name: string;
  description: string;

  // ── CSS Custom Property values injected at runtime ──
  bgPrimary: string;        // Main strip background
  bgSecondary: string;      // Batter/bowler panel background
  bgAccent: string;         // Score box, team badge background
  bgTicker: string;         // Bottom ticker background
  bgGlass?: string;         // glassmorphism overlay color

  textPrimary: string;      // Main labels
  textSecondary: string;    // Sub-labels, secondary info
  textAccent: string;       // Highlighted numbers (score, strike)
  textMuted: string;        // Balls, SR, economy — muted

  accentPrimary: string;    // Main accent (borders, glows, badges)
  accentSecondary: string;  // Secondary accent
  accentGold?: string;      // Optional gold for special moments

  borderColor: string;      // Panel borders
  glowColor: string;        // CSS box-shadow glow color
  glowStrength: string;     // e.g. '0 0 20px'

  // Ball dot colors
  ballDot0: string;         // dot ball
  ballDot1: string;         // 1 run
  ballDot4: string;         // four
  ballDot6: string;         // six
  ballDotW: string;         // wicket
  ballDotWD: string;        // wide
  ballDotNB: string;        // no-ball

  // Flash colors
  flashFour: string;
  flashSix: string;
  flashWicket: string;
  flashExtra: string;

  // Fonts
  fontPrimary: string;      // Google Fonts family name
  fontMono?: string;        // Monospace for digits
  fontUrl?: string;         // Google Fonts @import URL

  // Layout & animation
  layoutVariant: LayoutVariant;
  animationVariant: AnimationVariant;
  celebrationStyle: CelebrationStyle;

  // Visual style
  borderRadius: string;     // Border radius tokens
  stripHeight: string;      // px height of main strip
  backdropBlur?: string;    // for glass themes
  backgroundPattern?: string; // CSS gradient/pattern for body
  teamBadgeStyle: 'pill' | 'square' | 'angled' | 'circle';

  // Special flags
  isLight: boolean;         // light theme → invert some defaults
  hasAnimatedBg: boolean;   // animated gradient background
  showHundredBalls: boolean; // The Hundred layout — show 100-ball counter
}

// =============================================================================
// THEME DEFINITIONS
// =============================================================================

export const SCOREBOARD_THEMES: Record<ThemeId, ScoreboardTheme> = {
  // ── 1. NAKSHATRA ─────────────────────────────────────────────────────────────
  nakshatra: {
    id: 'nakshatra',
    name: 'Nakshatra',
    description: 'Glowing purple/indigo cosmic gradient, gold highlights',
    bgPrimary: 'linear-gradient(135deg, #1e0b36 0%, #0c0218 100%)',
    bgSecondary: '#0c0218',
    bgAccent: '#ffd700',
    bgTicker: '#0c0218',
    textPrimary: '#ffffff',
    textSecondary: '#d1bcf5',
    textAccent: '#ffd700',
    textMuted: '#a084c8',
    accentPrimary: '#ffd700',
    accentSecondary: '#c084fc',
    borderColor: 'rgba(255, 215, 0, 0.25)',
    glowColor: 'rgba(255, 215, 0, 0.35)',
    glowStrength: '0 0 15px',
    ballDot0: '#23123a',
    ballDot1: '#3c1d66',
    ballDot4: '#ffd700',
    ballDot6: '#22c55e',
    ballDotW: '#ef4444',
    ballDotWD: '#a855f7',
    ballDotNB: '#f97316',
    flashFour: '#ffd700',
    flashSix: '#22c55e',
    flashWicket: '#ef4444',
    flashExtra: '#ffd700',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'standard',
    animationVariant: 'slot-machine',
    celebrationStyle: 'ticker-takeover',
    borderRadius: '8px',
    stripHeight: '74px',
    teamBadgeStyle: 'circle',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 2. AGNI ──────────────────────────────────────────────────────────────────
  agni: {
    id: 'agni',
    name: 'Agni',
    description: 'Fiery red/orange angles, high-contrast borders',
    bgPrimary: '#b91c1c',
    bgSecondary: '#1e1b4b',
    bgAccent: '#f97316',
    bgTicker: '#1e1b4b',
    textPrimary: '#ffffff',
    textSecondary: '#fca5a5',
    textAccent: '#f97316',
    textMuted: '#fca5a5',
    accentPrimary: '#f97316',
    accentSecondary: '#b91c1c',
    borderColor: '#f97316',
    glowColor: 'rgba(249, 115, 22, 0.5)',
    glowStrength: '0 0 10px',
    ballDot0: '#111827',
    ballDot1: '#1e293b',
    ballDot4: '#f97316',
    ballDot6: '#10b981',
    ballDotW: '#ef4444',
    ballDotWD: '#8b5cf6',
    ballDotNB: '#f97316',
    flashFour: '#f97316',
    flashSix: '#10b981',
    flashWicket: '#ef4444',
    flashExtra: '#fbbf24',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'centered',
    animationVariant: 'flip',
    celebrationStyle: 'page-center',
    borderRadius: '0px',
    stripHeight: '76px',
    teamBadgeStyle: 'angled',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 3. APEX ──────────────────────────────────────────────────────────────────
  apex: {
    id: 'apex',
    name: 'Apex',
    description: 'Flat ultra-minimal slate white and black',
    bgPrimary: '#ffffff',
    bgSecondary: '#000000',
    bgAccent: '#000000',
    bgTicker: '#000000',
    textPrimary: '#000000',
    textSecondary: '#666666',
    textAccent: '#ffffff',
    textMuted: '#666666',
    accentPrimary: '#000000',
    accentSecondary: '#ffffff',
    borderColor: '#000000',
    glowColor: 'rgba(0,0,0,0)',
    glowStrength: 'none',
    ballDot0: '#f1f5f9',
    ballDot1: '#e2e8f0',
    ballDot4: '#000000',
    ballDot6: '#000000',
    ballDotW: '#000000',
    ballDotWD: '#666666',
    ballDotNB: '#666666',
    flashFour: '#000000',
    flashSix: '#000000',
    flashWicket: '#000000',
    flashExtra: '#666666',
    fontPrimary: "'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'standard',
    animationVariant: 'fade',
    celebrationStyle: 'batter-bar',
    borderRadius: '0px',
    stripHeight: '72px',
    teamBadgeStyle: 'square',
    isLight: true,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 4. ARANYAKA ──────────────────────────────────────────────────────────────
  aranyaka: {
    id: 'aranyaka',
    name: 'Aranyaka',
    description: 'Forest green/teal organic layout, gold typography',
    bgPrimary: '#064e3b',
    bgSecondary: '#022c22',
    bgAccent: '#fbbf24',
    bgTicker: '#022c22',
    textPrimary: '#ffffff',
    textSecondary: '#a7f3d0',
    textAccent: '#fbbf24',
    textMuted: '#a7f3d0',
    accentPrimary: '#fbbf24',
    accentSecondary: '#fbbf24',
    borderColor: 'rgba(251, 191, 36, 0.3)',
    glowColor: 'rgba(0, 0, 0, 0.15)',
    glowStrength: '0 4px 6px',
    ballDot0: '#042f1a',
    ballDot1: '#064e3b',
    ballDot4: '#fbbf24',
    ballDot6: '#34d399',
    ballDotW: '#f87171',
    ballDotWD: '#a78bfa',
    ballDotNB: '#fbbf24',
    flashFour: '#fbbf24',
    flashSix: '#34d399',
    flashWicket: '#ef4444',
    flashExtra: '#fbbf24',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'pill',
    animationVariant: 'typewriter',
    celebrationStyle: 'ticker-takeover',
    borderRadius: '12px',
    stripHeight: '72px',
    teamBadgeStyle: 'circle',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 5. VOLT ──────────────────────────────────────────────────────────────────
  volt: {
    id: 'volt',
    name: 'Volt',
    description: 'Charcoal black, vibrant neon lime highlights',
    bgPrimary: '#171717',
    bgSecondary: '#0a0a0a',
    bgAccent: '#a3e635',
    bgTicker: '#0a0a0a',
    textPrimary: '#ffffff',
    textSecondary: '#a3a3a3',
    textAccent: '#a3e635',
    textMuted: '#737373',
    accentPrimary: '#a3e635',
    accentSecondary: '#a3e635',
    borderColor: '#a3e635',
    glowColor: 'rgba(163, 230, 53, 0.4)',
    glowStrength: '0 0 12px',
    ballDot0: '#171717',
    ballDot1: '#262626',
    ballDot4: '#a3e635',
    ballDot6: '#22c55e',
    ballDotW: '#ef4444',
    ballDotWD: '#a855f7',
    ballDotNB: '#f97316',
    flashFour: '#a3e635',
    flashSix: '#22c55e',
    flashWicket: '#ef4444',
    flashExtra: '#a3e635',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'centered',
    animationVariant: 'slot-machine',
    celebrationStyle: 'batter-bar',
    borderRadius: '2px',
    stripHeight: '76px',
    teamBadgeStyle: 'angled',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 6. THUNDER ───────────────────────────────────────────────────────────────
  thunder: {
    id: 'thunder',
    name: 'Thunder',
    description: 'Slate grey with neon cyan electricity accents',
    bgPrimary: '#1e293b',
    bgSecondary: '#0f172a',
    bgAccent: '#06b6d4',
    bgTicker: '#0f172a',
    textPrimary: '#ffffff',
    textSecondary: '#94a3b8',
    textAccent: '#06b6d4',
    textMuted: '#64748b',
    accentPrimary: '#06b6d4',
    accentSecondary: '#06b6d4',
    borderColor: '#06b6d4',
    glowColor: 'rgba(6, 182, 212, 0.5)',
    glowStrength: '0 0 14px',
    ballDot0: '#1e293b',
    ballDot1: '#334155',
    ballDot4: '#06b6d4',
    ballDot6: '#22c55e',
    ballDotW: '#ef4444',
    ballDotWD: '#a855f7',
    ballDotNB: '#f97316',
    flashFour: '#06b6d4',
    flashSix: '#22c55e',
    flashWicket: '#ef4444',
    flashExtra: '#06b6d4',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'standard',
    animationVariant: 'flip',
    celebrationStyle: 'page-center',
    borderRadius: '6px',
    stripHeight: '74px',
    teamBadgeStyle: 'angled',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 7. AFRICA ────────────────────────────────────────────────────────────────
  africa: {
    id: 'africa',
    name: 'Africa',
    description: 'Warm earth-toned gradient (ochre, clay, dark wood)',
    bgPrimary: '#7c2d12',
    bgSecondary: '#431407',
    bgAccent: '#f59e0b',
    bgTicker: '#431407',
    textPrimary: '#fffbeb',
    textSecondary: '#fed7aa',
    textAccent: '#f59e0b',
    textMuted: '#d97706',
    accentPrimary: '#f59e0b',
    accentSecondary: '#ea580c',
    borderColor: '#ea580c',
    glowColor: 'rgba(0,0,0,0)',
    glowStrength: 'none',
    ballDot0: '#431407',
    ballDot1: '#7c2d12',
    ballDot4: '#f59e0b',
    ballDot6: '#10b981',
    ballDotW: '#dc2626',
    ballDotWD: '#8b5cf6',
    ballDotNB: '#ea580c',
    flashFour: '#f59e0b',
    flashSix: '#10b981',
    flashWicket: '#dc2626',
    flashExtra: '#f59e0b',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'pill',
    animationVariant: 'typewriter',
    celebrationStyle: 'ticker-takeover',
    borderRadius: '10px',
    stripHeight: '72px',
    teamBadgeStyle: 'circle',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 8. ELITE ─────────────────────────────────────────────────────────────────
  elite: {
    id: 'elite',
    name: 'Elite',
    description: 'Monochromatic dark velvet, champagne gold text',
    bgPrimary: '#111111',
    bgSecondary: '#1c1917',
    bgAccent: '#d97706',
    bgTicker: '#1c1917',
    textPrimary: '#fafaf9',
    textSecondary: '#d6d3d1',
    textAccent: '#d97706',
    textMuted: '#a8a29e',
    accentPrimary: '#d97706',
    accentSecondary: '#d97706',
    borderColor: '#d97706',
    glowColor: 'rgba(217, 119, 6, 0.25)',
    glowStrength: '0 0 8px',
    ballDot0: '#1c1917',
    ballDot1: '#292524',
    ballDot4: '#d97706',
    ballDot6: '#16a34a',
    ballDotW: '#dc2626',
    ballDotWD: '#a855f7',
    ballDotNB: '#f97316',
    flashFour: '#d97706',
    flashSix: '#16a34a',
    flashWicket: '#dc2626',
    flashExtra: '#d97706',
    fontPrimary: "'Playfair Display', serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,600;1,600&display=swap',
    layoutVariant: 'standard',
    animationVariant: 'fade',
    celebrationStyle: 'batter-bar',
    borderRadius: '0px',
    stripHeight: '76px',
    teamBadgeStyle: 'square',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 9. FRANCHISE ─────────────────────────────────────────────────────────────
  franchise: {
    id: 'franchise',
    name: 'Franchise',
    description: 'Sporty cobalt blue, bright magenta highlights',
    bgPrimary: '#1e3a8a',
    bgSecondary: '#172554',
    bgAccent: '#ec4899',
    bgTicker: '#172554',
    textPrimary: '#ffffff',
    textSecondary: '#bfdbfe',
    textAccent: '#ec4899',
    textMuted: '#93c5fd',
    accentPrimary: '#ec4899',
    accentSecondary: '#ec4899',
    borderColor: '#ec4899',
    glowColor: 'rgba(236, 72, 153, 0.4)',
    glowStrength: '0 0 10px',
    ballDot0: '#1e293b',
    ballDot1: '#334155',
    ballDot4: '#ec4899',
    ballDot6: '#10b981',
    ballDotW: '#ef4444',
    ballDotWD: '#a855f7',
    ballDotNB: '#f97316',
    flashFour: '#ec4899',
    flashSix: '#10b981',
    flashWicket: '#ef4444',
    flashExtra: '#ec4899',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'centered',
    animationVariant: 'flip',
    celebrationStyle: 'page-center',
    borderRadius: '6px',
    stripHeight: '74px',
    teamBadgeStyle: 'angled',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 10. BLITZ ────────────────────────────────────────────────────────────────
  blitz: {
    id: 'blitz',
    name: 'Blitz',
    description: 'High-energy cyberpunk neon pink and teal',
    bgPrimary: '#030712',
    bgSecondary: '#0b0f19',
    bgAccent: '#ff007f',
    bgTicker: '#0b0f19',
    textPrimary: '#ffffff',
    textSecondary: '#00f3ff',
    textAccent: '#ff007f',
    textMuted: '#00f3ff',
    accentPrimary: '#ff007f',
    accentSecondary: '#00f3ff',
    borderColor: '#00f3ff',
    glowColor: 'rgba(255, 0, 127, 0.6)',
    glowStrength: '0 0 15px',
    ballDot0: '#0f172a',
    ballDot1: '#1e293b',
    ballDot4: '#ff007f',
    ballDot6: '#22c55e',
    ballDotW: '#ef4444',
    ballDotWD: '#00f3ff',
    ballDotNB: '#ff007f',
    flashFour: '#ff007f',
    flashSix: '#22c55e',
    flashWicket: '#ef4444',
    flashExtra: '#00f3ff',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'standard',
    animationVariant: 'slot-machine',
    celebrationStyle: 'ticker-takeover',
    borderRadius: '4px',
    stripHeight: '78px',
    teamBadgeStyle: 'angled',
    isLight: false,
    hasAnimatedBg: true,
    showHundredBalls: false,
  },

  // ── 11. ASIA 2021 ────────────────────────────────────────────────────────────
  asia2021: {
    id: 'asia2021',
    name: 'Asia 2021',
    description: 'Classic subcontinent 2021 (deep teal & rose red)',
    bgPrimary: '#065f46',
    bgSecondary: '#064e3b',
    bgAccent: '#fb7185',
    bgTicker: '#064e3b',
    textPrimary: '#ffffff',
    textSecondary: '#fecdd3',
    textAccent: '#fb7185',
    textMuted: '#fecdd3',
    accentPrimary: '#fb7185',
    accentSecondary: '#fb7185',
    borderColor: '#fb7185',
    glowColor: 'rgba(0,0,0,0)',
    glowStrength: 'none',
    ballDot0: '#042f1a',
    ballDot1: '#064e3b',
    ballDot4: '#fb7185',
    ballDot6: '#34d399',
    ballDotW: '#f87171',
    ballDotWD: '#a78bfa',
    ballDotNB: '#fb7185',
    flashFour: '#fb7185',
    flashSix: '#34d399',
    flashWicket: '#f87171',
    flashExtra: '#fb7185',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'standard',
    animationVariant: 'typewriter',
    celebrationStyle: 'ticker-takeover',
    borderRadius: '4px',
    stripHeight: '74px',
    teamBadgeStyle: 'pill',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 12. ASIA 2022 ────────────────────────────────────────────────────────────
  asia2022: {
    id: 'asia2022',
    name: 'Asia 2022',
    description: 'Classic subcontinent 2022 (royal blue & gold)',
    bgPrimary: '#1d4ed8',
    bgSecondary: '#1e3a8a',
    bgAccent: '#eab308',
    bgTicker: '#1e3a8a',
    textPrimary: '#ffffff',
    textSecondary: '#bfdbfe',
    textAccent: '#eab308',
    textMuted: '#93c5fd',
    accentPrimary: '#eab308',
    accentSecondary: '#eab308',
    borderColor: '#eab308',
    glowColor: 'rgba(0,0,0,0)',
    glowStrength: 'none',
    ballDot0: '#172554',
    ballDot1: '#1e3a8a',
    ballDot4: '#eab308',
    ballDot6: '#10b981',
    ballDotW: '#ef4444',
    ballDotWD: '#a855f7',
    ballDotNB: '#eab308',
    flashFour: '#eab308',
    flashSix: '#10b981',
    flashWicket: '#ef4444',
    flashExtra: '#eab308',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'standard',
    animationVariant: 'flip',
    celebrationStyle: 'page-center',
    borderRadius: '4px',
    stripHeight: '74px',
    teamBadgeStyle: 'pill',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 13. ASIA ─────────────────────────────────────────────────────────────────
  asia: {
    id: 'asia',
    name: 'Asia Standard',
    description: 'Subcontinent traditional (teal & amber)',
    bgPrimary: '#0f766e',
    bgSecondary: '#115e59',
    bgAccent: '#f59e0b',
    bgTicker: '#115e59',
    textPrimary: '#ffffff',
    textSecondary: '#ccfbf1',
    textAccent: '#f59e0b',
    textMuted: '#99f6e4',
    accentPrimary: '#f59e0b',
    accentSecondary: '#f59e0b',
    borderColor: 'rgba(255, 255, 255, 0.15)',
    glowColor: 'rgba(0,0,0,0)',
    glowStrength: 'none',
    ballDot0: '#115e59',
    ballDot1: '#0f766e',
    ballDot4: '#f59e0b',
    ballDot6: '#10b981',
    ballDotW: '#ef4444',
    ballDotWD: '#a855f7',
    ballDotNB: '#f59e0b',
    flashFour: '#f59e0b',
    flashSix: '#10b981',
    flashWicket: '#ef4444',
    flashExtra: '#f59e0b',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'pill',
    animationVariant: 'slot-machine',
    celebrationStyle: 'ticker-takeover',
    borderRadius: '6px',
    stripHeight: '72px',
    teamBadgeStyle: 'pill',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 14. CHAMPIONSHIP 2019 ────────────────────────────────────────────────────
  championship2019: {
    id: 'championship2019',
    name: 'Championship 2019',
    description: 'Dark metallic carbon, gold lines',
    bgPrimary: '#1c1917',
    bgSecondary: '#0c0a09',
    bgAccent: '#ca8a04',
    bgTicker: '#0c0a09',
    textPrimary: '#ffffff',
    textSecondary: '#d6d3d1',
    textAccent: '#ca8a04',
    textMuted: '#a8a29e',
    accentPrimary: '#ca8a04',
    accentSecondary: '#ca8a04',
    borderColor: '#ca8a04',
    glowColor: 'rgba(0,0,0,0)',
    glowStrength: 'none',
    ballDot0: '#1c1917',
    ballDot1: '#292524',
    ballDot4: '#ca8a04',
    ballDot6: '#16a34a',
    ballDotW: '#dc2626',
    ballDotWD: '#a855f7',
    ballDotNB: '#f97316',
    flashFour: '#ca8a04',
    flashSix: '#16a34a',
    flashWicket: '#dc2626',
    flashExtra: '#ca8a04',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'centered',
    animationVariant: 'flip',
    celebrationStyle: 'batter-bar',
    borderRadius: '2px',
    stripHeight: '76px',
    teamBadgeStyle: 'angled',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 15. CHAMPIONSHIP 2022 ────────────────────────────────────────────────────
  championship2022: {
    id: 'championship2022',
    name: 'Championship 2022',
    description: 'Steel blue-gray, silver highlights',
    bgPrimary: '#334155',
    bgSecondary: '#1e293b',
    bgAccent: '#f1f5f9',
    bgTicker: '#1e293b',
    textPrimary: '#ffffff',
    textSecondary: '#cbd5e1',
    textAccent: '#f1f5f9',
    textMuted: '#94a3b8',
    accentPrimary: '#f1f5f9',
    accentSecondary: '#f1f5f9',
    borderColor: '#f1f5f9',
    glowColor: 'rgba(0,0,0,0)',
    glowStrength: 'none',
    ballDot0: '#1e293b',
    ballDot1: '#334155',
    ballDot4: '#f1f5f9',
    ballDot6: '#10b981',
    ballDotW: '#ef4444',
    ballDotWD: '#a855f7',
    ballDotNB: '#f97316',
    flashFour: '#f1f5f9',
    flashSix: '#10b981',
    flashWicket: '#ef4444',
    flashExtra: '#f1f5f9',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'standard',
    animationVariant: 'slot-machine',
    celebrationStyle: 'page-center',
    borderRadius: '4px',
    stripHeight: '74px',
    teamBadgeStyle: 'angled',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 16. DHARMA ───────────────────────────────────────────────────────────────
  dharma: {
    id: 'dharma',
    name: 'Dharma',
    description: 'Saffron orange, warm gold highlights',
    bgPrimary: '#ea580c',
    bgSecondary: '#9a3412',
    bgAccent: '#eab308',
    bgTicker: '#9a3412',
    textPrimary: '#ffffff',
    textSecondary: '#ffedd5',
    textAccent: '#eab308',
    textMuted: '#ffedd5',
    accentPrimary: '#eab308',
    accentSecondary: '#ea580c',
    borderColor: '#eab308',
    glowColor: 'rgba(234, 88, 12, 0.3)',
    glowStrength: '0 0 10px',
    ballDot0: '#7c2d12',
    ballDot1: '#9a3412',
    ballDot4: '#eab308',
    ballDot6: '#22c55e',
    ballDotW: '#ef4444',
    ballDotWD: '#a855f7',
    ballDotNB: '#ea580c',
    flashFour: '#eab308',
    flashSix: '#22c55e',
    flashWicket: '#ef4444',
    flashExtra: '#eab308',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'pill',
    animationVariant: 'typewriter',
    celebrationStyle: 'ticker-takeover',
    borderRadius: '8px',
    stripHeight: '72px',
    teamBadgeStyle: 'pill',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 17. SHAKTI ───────────────────────────────────────────────────────────────
  shakti: {
    id: 'shakti',
    name: 'Shakti',
    description: 'Crimson red, burning gold highlights',
    bgPrimary: '#991b1b',
    bgSecondary: '#7f1d1d',
    bgAccent: '#f59e0b',
    bgTicker: '#7f1d1d',
    textPrimary: '#ffffff',
    textSecondary: '#fee2e2',
    textAccent: '#f59e0b',
    textMuted: '#fee2e2',
    accentPrimary: '#f59e0b',
    accentSecondary: '#991b1b',
    borderColor: '#f59e0b',
    glowColor: 'rgba(153, 27, 27, 0.4)',
    glowStrength: '0 0 12px',
    ballDot0: '#7f1d1d',
    ballDot1: '#991b1b',
    ballDot4: '#f59e0b',
    ballDot6: '#10b981',
    ballDotW: '#ef4444',
    ballDotWD: '#a855f7',
    ballDotNB: '#f59e0b',
    flashFour: '#f59e0b',
    flashSix: '#10b981',
    flashWicket: '#ef4444',
    flashExtra: '#f59e0b',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'standard',
    animationVariant: 'flip',
    celebrationStyle: 'page-center',
    borderRadius: '0px',
    stripHeight: '76px',
    teamBadgeStyle: 'angled',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 18. BUZZ ─────────────────────────────────────────────────────────────────
  buzz: {
    id: 'buzz',
    name: 'Buzz',
    description: 'Cyber yellow, black grid background',
    bgPrimary: '#000000',
    bgSecondary: '#171717',
    bgAccent: '#eab308',
    bgTicker: '#171717',
    textPrimary: '#ffffff',
    textSecondary: '#a3a3a3',
    textAccent: '#eab308',
    textMuted: '#a3a3a3',
    accentPrimary: '#eab308',
    accentSecondary: '#eab308',
    borderColor: '#eab308',
    glowColor: 'rgba(234, 179, 8, 0.35)',
    glowStrength: '0 0 10px',
    ballDot0: '#171717',
    ballDot1: '#262626',
    ballDot4: '#eab308',
    ballDot6: '#22c55e',
    ballDotW: '#ef4444',
    ballDotWD: '#a855f7',
    ballDotNB: '#eab308',
    flashFour: '#eab308',
    flashSix: '#22c55e',
    flashWicket: '#ef4444',
    flashExtra: '#eab308',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'centered',
    animationVariant: 'slot-machine',
    celebrationStyle: 'batter-bar',
    borderRadius: '4px',
    stripHeight: '74px',
    teamBadgeStyle: 'square',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },

  // ── 19. DIAMOND ──────────────────────────────────────────────────────────────
  diamond: {
    id: 'diamond',
    name: 'Diamond',
    description: 'Pale ice blue, crystalline sapphire',
    bgPrimary: '#0f766e',
    bgSecondary: '#134e4a',
    bgAccent: '#22d3ee',
    bgTicker: '#134e4a',
    textPrimary: '#e0f7fa',
    textSecondary: '#22d3ee',
    textAccent: '#22d3ee',
    textMuted: '#22d3ee',
    accentPrimary: '#22d3ee',
    accentSecondary: '#22d3ee',
    borderColor: '#22d3ee',
    glowColor: 'rgba(34, 211, 238, 0.4)',
    glowStrength: '0 0 15px',
    ballDot0: '#115e59',
    ballDot1: '#0f766e',
    ballDot4: '#22d3ee',
    ballDot6: '#22c55e',
    ballDotW: '#ef4444',
    ballDotWD: '#00f3ff',
    ballDotNB: '#22d3ee',
    flashFour: '#22d3ee',
    flashSix: '#22c55e',
    flashWicket: '#ef4444',
    flashExtra: '#00f3ff',
    fontPrimary: "'Outfit', 'Inter', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800;900&display=swap',
    layoutVariant: 'pill',
    animationVariant: 'typewriter',
    celebrationStyle: 'ticker-takeover',
    borderRadius: '12px',
    stripHeight: '72px',
    teamBadgeStyle: 'circle',
    isLight: false,
    hasAnimatedBg: false,
    showHundredBalls: false,
  },
};

export const DEFAULT_THEME_ID: ThemeId = 'nakshatra';

/** Get a theme by ID, falling back to nakshatra */
export function getTheme(id: string | null | undefined): ScoreboardTheme {
  if (id && id in SCOREBOARD_THEMES) {
    return SCOREBOARD_THEMES[id as ThemeId];
  }
  return SCOREBOARD_THEMES[DEFAULT_THEME_ID];
}

/** Inject a theme's CSS custom properties onto a DOM element */
export function applyThemeToDom(theme: ScoreboardTheme, el: HTMLElement = document.documentElement): void {
  const vars: Record<string, string> = {
    '--sb-bg-primary': theme.bgPrimary,
    '--sb-bg-secondary': theme.bgSecondary,
    '--sb-bg-accent': theme.bgAccent,
    '--sb-bg-ticker': theme.bgTicker,
    '--sb-text-primary': theme.textPrimary,
    '--sb-text-secondary': theme.textSecondary,
    '--sb-text-accent': theme.textAccent,
    '--sb-text-muted': theme.textMuted,
    '--sb-accent-primary': theme.accentPrimary,
    '--sb-accent-secondary': theme.accentSecondary,
    '--sb-accent-gold': theme.accentGold ?? theme.accentPrimary,
    '--sb-border-color': theme.borderColor,
    '--sb-glow-color': theme.glowColor,
    '--sb-glow-strength': theme.glowStrength,
    '--sb-ball-dot-0': theme.ballDot0,
    '--sb-ball-dot-1': theme.ballDot1,
    '--sb-ball-dot-4': theme.ballDot4,
    '--sb-ball-dot-6': theme.ballDot6,
    '--sb-ball-dot-w': theme.ballDotW,
    '--sb-ball-dot-wd': theme.ballDotWD,
    '--sb-ball-dot-nb': theme.ballDotNB,
    '--sb-flash-four': theme.flashFour,
    '--sb-flash-six': theme.flashSix,
    '--sb-flash-wicket': theme.flashWicket,
    '--sb-flash-extra': theme.flashExtra,
    '--sb-font-primary': theme.fontPrimary,
    '--sb-font-mono': theme.fontMono ?? theme.fontPrimary,
    '--sb-border-radius': theme.borderRadius,
    '--sb-strip-height': theme.stripHeight,
    '--sb-backdrop-blur': theme.backdropBlur ?? '0px',
  };
  for (const [k, v] of Object.entries(vars)) {
    el.style.setProperty(k, v);
  }
}

/** List of all theme IDs for iteration */
export const ALL_THEME_IDS: ThemeId[] = Object.keys(SCOREBOARD_THEMES) as ThemeId[];
