import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Check, Copy, Tv } from 'lucide-react';
import { CricNavbar } from '../common/CricNavbar';
export const THEME_LINKS_DATA = [
    { id: '1', name: 'Asia Cup', server1Url: '/#/theme/1/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=asia_cup', mobileUrl: '/#/overlay?theme=asia_cup&mobile=true' },
    { id: '2', name: 'CWC 19', server1Url: '/#/theme/2/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=cwc19', mobileUrl: '/#/overlay?theme=cwc19&mobile=true' },
    { id: '3', name: 'Champions Trophy 2025', server1Url: '/#/theme/3/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=ct2025', mobileUrl: '/#/overlay?theme=ct2025&mobile=true' },
    { id: '4', name: 'CWC Womens 25 India', server1Url: '/#/theme/4/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=cwc_women25', mobileUrl: '/#/overlay?theme=cwc_women25&mobile=true', badge: 'NEW' },
    { id: '5', name: 'WCL (Fancode)', server1Url: '/#/theme/5/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=wcl_fancode', mobileUrl: '/#/overlay?theme=wcl_fancode&mobile=true' },
    { id: '6', name: 'CWC 23 India 2.0', server1Url: '/#/theme/6/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=cwc23', mobileUrl: '/#/overlay?theme=cwc23&mobile=true' },
    { id: '7', name: 'BBL Black', server1Url: '/#/theme/7/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=bbl_black', mobileUrl: '/#/overlay?theme=bbl_black&mobile=true' },
    { id: '8', name: 'CricFusion Theme', server1Url: '/#/theme/8/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=cricfusion', mobileUrl: '/#/overlay?theme=cricfusion&mobile=true' },
    { id: '9', name: 'T20 EMERGING ASIA CUP 2024', server1Url: '/#/theme/9/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=t20_asia24', mobileUrl: '/#/overlay?theme=t20_asia24&mobile=true' },
    { id: '10', name: 'SA20', server1Url: '/#/theme/10/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=sa20', mobileUrl: '/#/overlay?theme=sa20&mobile=true' },
    { id: '11', name: 'Jio Cinema', server1Url: '/#/theme/11/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=jiocinema', mobileUrl: '/#/overlay?theme=jiocinema&mobile=true' },
    { id: '12', name: 'IPL', server1Url: '/#/theme/12/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=ipl', mobileUrl: '/#/overlay?theme=ipl&mobile=true' },
    { id: '13', name: 'WT20 2024', server1Url: '/#/theme/13/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=wt20_2024', mobileUrl: '/#/overlay?theme=wt20_2024&mobile=true' },
    { id: '14', name: 'BBL Star Sports', server1Url: '/#/theme/14/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=bbl_star', mobileUrl: '/#/overlay?theme=bbl_star&mobile=true' },
    { id: '15', name: 'IPL 25', server1Url: '/#/theme/15/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=ipl25', mobileUrl: '/#/overlay?theme=ipl25&mobile=true' },
    { id: '16', name: 'CricPic Theme', server1Url: '/#/theme/16/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=cricpic', mobileUrl: '/#/overlay?theme=cricpic&mobile=true', badge: 'TOP' },
    { id: '17', name: 'CWC 23 India (Diwali Edition)', server1Url: '/#/theme/17/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=cwc23_diwali', mobileUrl: '/#/overlay?theme=cwc23_diwali&mobile=true', badge: 'SPECIAL' },
    { id: '18', name: 'BBL White', server1Url: '/#/theme/18/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=bbl_white', mobileUrl: '/#/overlay?theme=bbl_white&mobile=true' },
    { id: '19', name: 'ICC T20 World Cup 2020', server1Url: '/#/theme/19/69d9cec52b632413dd8d7d48', server2Url: '/#/overlay?theme=cwc_t20_2020', mobileUrl: '/#/overlay?theme=cwc_t20_2020&mobile=true' },
];
export const ThemeLinksPage = () => {
    const [copiedKey, setCopiedKey] = useState(null);
    const handleCopy = (path, key) => {
        const fullUrl = `${window.location.origin}${path}`;
        navigator.clipboard.writeText(fullUrl);
        setCopiedKey(key);
        setTimeout(() => setCopiedKey(null), 2000);
    };
    return (_jsxs("div", { className: "min-h-screen bg-[#0a0f1d] text-slate-100 font-sans", children: [_jsx(CricNavbar, {}), _jsxs("main", { className: "max-w-6xl mx-auto py-10 px-4", children: [_jsxs("div", { className: "text-center mb-8", children: [_jsx("h1", { className: "text-4xl font-black uppercase tracking-wider text-white mb-2", children: "ALL SCOREBOARD LINKS" }), _jsxs("p", { className: "text-slate-400 text-sm font-semibold", children: ["Copy any link from ", _jsx("span", { className: "text-amber-400 font-bold", children: "Server 1" }), " or ", _jsx("span", { className: "text-cyan-400 font-bold", children: "Server 2" }), " and add to your streaming app (OBS Studio, vMix, Prism Live)."] })] }), _jsx("div", { className: "bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-2xl", children: _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-left border-collapse", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-slate-950 border-b border-slate-800 text-slate-400 uppercase text-xs tracking-wider font-extrabold", children: [_jsx("th", { className: "py-4 px-6 w-16 text-center", children: "No." }), _jsx("th", { className: "py-4 px-6", children: "Theme Name" }), _jsx("th", { className: "py-4 px-6 text-center w-36", children: "Server 1" }), _jsx("th", { className: "py-4 px-6 text-center w-36", children: "Server 2" }), _jsx("th", { className: "py-4 px-6 text-center w-44", children: "Mobile Stream Link" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-800 text-sm font-bold", children: THEME_LINKS_DATA.map((item) => {
                                            const s1Key = `${item.id}-s1`;
                                            const s2Key = `${item.id}-s2`;
                                            const mobKey = `${item.id}-mob`;
                                            return (_jsxs("tr", { className: "hover:bg-slate-850/50 transition-all", children: [_jsx("td", { className: "py-3.5 px-6 text-center text-slate-500 font-mono", children: item.id }), _jsxs("td", { className: "py-3.5 px-6 text-white font-extrabold flex items-center gap-2", children: [item.name, item.badge && (_jsx("span", { className: "bg-cyan-500/20 text-cyan-300 text-[10px] px-2 py-0.5 rounded font-black border border-cyan-400/40", children: item.badge }))] }), _jsx("td", { className: "py-3.5 px-6 text-center", children: _jsxs("button", { onClick: () => handleCopy(item.server1Url, s1Key), className: "w-full py-2 bg-slate-950 hover:bg-slate-800 text-slate-200 hover:text-white font-bold rounded-lg border border-slate-700 flex items-center justify-center gap-1.5 transition-all active:scale-95 text-xs shadow", children: [copiedKey === s1Key ? _jsx(Check, { className: "w-3.5 h-3.5 text-emerald-400" }) : _jsx(Copy, { className: "w-3.5 h-3.5 text-amber-400" }), copiedKey === s1Key ? 'Copied' : 'Copy'] }) }), _jsx("td", { className: "py-3.5 px-6 text-center", children: _jsxs("button", { onClick: () => handleCopy(item.server2Url, s2Key), className: "w-full py-2 bg-slate-950 hover:bg-slate-800 text-slate-200 hover:text-white font-bold rounded-lg border border-slate-700 flex items-center justify-center gap-1.5 transition-all active:scale-95 text-xs shadow", children: [copiedKey === s2Key ? _jsx(Check, { className: "w-3.5 h-3.5 text-emerald-400" }) : _jsx(Copy, { className: "w-3.5 h-3.5 text-cyan-400" }), copiedKey === s2Key ? 'Copied' : 'Copy'] }) }), _jsx("td", { className: "py-3.5 px-6 text-center", children: _jsxs("button", { onClick: () => handleCopy(item.mobileUrl, mobKey), className: "w-full py-2 bg-slate-950 hover:bg-slate-800 text-slate-200 hover:text-white font-bold rounded-lg border border-slate-700 flex items-center justify-center gap-1.5 transition-all active:scale-95 text-xs shadow", children: [copiedKey === mobKey ? _jsx(Check, { className: "w-3.5 h-3.5 text-emerald-400" }) : _jsx(Tv, { className: "w-3.5 h-3.5 text-purple-400" }), copiedKey === mobKey ? 'Copied' : 'Copy'] }) })] }, item.id));
                                        }) })] }) }) })] })] }));
};
