import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useLocation } from 'react-router-dom';
import { HardDrive, ShieldCheck, Tv, Radio, Palette, Trophy, Sliders } from 'lucide-react';
export const CricNavbar = () => {
    const location = useLocation();
    const isActive = (path) => {
        if (path === '/' && location.pathname === '/')
            return true;
        return location.pathname.startsWith(path) && path !== '/';
    };
    return (_jsxs("header", { className: "bg-[#0b1329] border-b border-slate-800 px-6 py-3.5 flex flex-wrap items-center justify-between gap-4 shadow-2xl sticky top-0 z-50", children: [_jsxs("div", { className: "flex items-center gap-6", children: [_jsxs(Link, { to: "/", className: "text-3xl font-black tracking-tight text-emerald-400 flex items-center gap-1.5 drop-shadow group", children: [_jsx(Radio, { className: "w-6 h-6 text-amber-400 animate-pulse group-hover:scale-110 transition-transform" }), _jsx("span", { children: "CricScorer" }), _jsx("span", { className: "text-cyan-400 font-extrabold italic", children: "PRO" })] }), _jsxs("nav", { className: "hidden md:flex items-center gap-6 font-bold text-sm text-slate-300", children: [_jsxs(Link, { to: "/", className: `flex items-center gap-1.5 transition-all ${location.pathname === '/' || location.pathname === '/control'
                                    ? 'text-cyan-400 border-b-2 border-cyan-400 pb-1 font-extrabold'
                                    : 'hover:text-cyan-300'}`, children: [_jsx(Sliders, { className: "w-4 h-4 text-emerald-400" }), " Control Studio"] }), _jsxs(Link, { to: "/tournament", className: `flex items-center gap-1.5 transition-all ${isActive('/tournament') ? 'text-cyan-400 border-b-2 border-cyan-400 pb-1 font-extrabold' : 'hover:text-cyan-300'}`, children: [_jsx(Trophy, { className: "w-4 h-4 text-amber-400" }), " Tournament"] }), _jsxs(Link, { to: "/theme_links", className: `flex items-center gap-1.5 transition-all ${isActive('/theme_links') ? 'text-cyan-400 border-b-2 border-cyan-400 pb-1 font-extrabold' : 'hover:text-cyan-300'}`, children: [_jsx(Palette, { className: "w-4 h-4 text-purple-400" }), " Scoreboard Links"] }), _jsxs(Link, { to: "/overlay", target: "_blank", className: "flex items-center gap-1.5 text-sky-400 hover:text-sky-300 transition-all", children: [_jsx(Tv, { className: "w-4 h-4" }), " OBS View \u2197"] })] })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "bg-cyan-500/10 border border-cyan-400/40 text-cyan-300 px-3 py-1.5 rounded-md text-xs font-mono font-bold flex items-center gap-1.5", children: [_jsx(HardDrive, { className: "w-4 h-4 text-cyan-400" }), " Storage: 1206/10000 kb"] }), _jsxs("div", { className: "bg-emerald-500/10 border border-emerald-400/40 text-emerald-300 px-3 py-1.5 rounded-md text-xs font-semibold flex items-center gap-1.5", children: [_jsx(ShieldCheck, { className: "w-4 h-4 text-emerald-400" }), " Account Expiry Date : 4/13/2026, 10:44:04 PM"] })] })] }));
};
